name: Check if a path has changes
description: see name
inputs:
  path:
    required: true
outputs:
  has-diff:
    description: thing
    value: ${{ steps.get-diff.outputs.has_diff}}

runs:
  using: "composite"
  steps:
    - id: get-diff
      shell: bash
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
          BEFORE='HEAD^1'
          AFTER='HEAD'
        else
          BEFORE=${{ github.event.before }}
          AFTER=${{ github.event.after }}
        fi
        if git diff $BEFORE $AFTER --name-only |
            grep ${{ inputs.path }}; then
          echo "has_diff=true" >> $GITHUB_OUTPUT
        else
          echo "has_diff=false" >> $GITHUB_OUTPUT
        fi
