name: Continuous Integration
on:
  push:
    branches: [main]

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"

  integrations:
    runs-on: ubuntu-latest
    needs: [say-hi]
    strategy:
      matrix:
        path: ["./integration_a", "./integration_b"]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: check for diff
        id: check-diff
        uses: ./.github/actions/check_path_diff
        with:
          path: ${{ matrix.path }}

      - name: run integration
        if: ${{ steps.check-diff.outputs.has-diff == 0 }}
        uses: ./.github/actions/run_integration
        with:
          path: ${{ matrix.path }}

  after:
    runs-on: ubuntu-latest
    needs: [integrations]
    steps:
      - run: echo "hello world"
