name: Continuous Integration
on:
  push:
    branches: [main]

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"

  integrations:
    runs-on: ubuntu-latest
    needs: [say-hi]
    strategy:
      matrix:
        path: ["./integration_a", "./integration_b"]
    uses: ./.github/workflows/int_a.yaml
    with:
      path: ${{ matrix.path }}

  after:
    runs-on: ubuntu-latest
    needs: [integrations]
    steps:
      - run: echo "hello world"
