name: Continuous Integration
on:
  push:
    branches: [main]

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps: 
      - run: |
      echo "Hello world"

  integrations:
    needs: [say-hi]
    strategy:
      matrix:
        path: ["./integration_a", "./integration_b"]
    steps:
      - name: Run integration ${{ matrix.path }}
        uses: ./.github/actions/run_integration
        with:
          path: ${{ matrix.path }}

  after:
    runs-on: ubuntu-latest
    needs: [integrations]
    steps:
      - run: |
      echo "finished"