on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  where-am-i:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: print location
       run: |
          echo "The current location is ${{ vars.MESSAGE }}"

