name: Integration A workflow

on:
  workflow_call:
    inputs:
      path:
        required: true
    paths:
      - ${{ inputs.path }}

jobs:
  print_path:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi from path
        run: echo "hello from ${{ inputs.path }}"
        shell: bash
