name: Manual Continuous Integration
on:
  workflow_call:
    inputs:
      environment:
        type: environment
      deploy_all:
        type: boolean
        default: false
      integration_b:
        type: boolean
        default: false
      integration_d:
        type: boolean
        default: false
      integration_a:
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      environment:
        type: environment
      deploy_all:
        type: boolean
        default: false
      integration_b:
        type: boolean
        default: false
      integration_d:
        type: boolean
        default: false
      integration_a:
        type: boolean
        default: false

jobs:
  get-integrations-to-deploy:
    runs-on: ubuntu-latest
    outputs:
      input-list: ${{ steps.get.outputs.input-list }}
    steps:
      - id: get
        run: |
          if ${{ inputs.deploy_all }}; then
            input_list=$(echo '${{ toJSON(inputs) }}' | jq -c 'with_entries(select(.key != "deploy_all" or .key != "environment")) | keys')
          else
            input_list=$(echo '${{ toJSON(inputs) }}' | jq -c 'with_entries(select(.value == true and .key != "deploy_all" or .key != "environment")) | keys')
          fi
          echo $input_list
          echo "input-list=$input_list" >> $GITHUB_OUTPUT
      - name: check
        if: steps.get.outputs.input-list == '[]'
        run: exit 1

  specific-integrations:
    runs-on: ubuntu-latest
    needs: [get-integrations-to-deploy]
    strategy:
      matrix:
        path: ${{ fromJSON(needs.get-integrations-to-deploy.outputs.input-list) }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: run integration
        uses: ./.github/actions/run_integration
        with:
          path: ${{ matrix.path }}

  after:
    runs-on: ubuntu-latest
    needs: [specific-integrations]
    steps:
      - run: echo "hello world"
