name: Manual Continuous Integration
on:
  workflow_dispatch:
    inputs:
      integration_b:
        type: boolean
        default: false
      integration_a:
        type: boolean
        default: false
      all:
        type: boolean
        default: false

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"

  integrations:
    runs-on: ubuntu-latest
    needs: [say-hi]
    strategy:
      matrix:
        path: ["integration_a", "integration_b"]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: check for diff
        id: check-diff
        uses: ./.github/actions/check_path_diff
        with:
          path: ${{ matrix.path }}

      - name: run integration
        if: ${{ steps.check-diff.outputs.has-diff == 'true' }}
        uses: ./.github/actions/run_integration
        with:
          path: ${{ matrix.path }}

  after:
    runs-on: ubuntu-latest
    needs: [integrations]
    steps:
      - run: echo "hello world"
