name: Manual Continuous Integration
on:
  workflow_dispatch:
    inputs:
      integration_b:
        type: boolean
        default: false
      integration_a:
        type: boolean
        default: false
      all:
        type: boolean
        default: false

jobs:
  get-input-list:
    runs-on: ubuntu-latest
    steps:
      - run: |
          input_list=$(echo "${{ toJSON(inputs) }}" | jq 'keys' -c)
          echo $input_list
          echo "input-list=$input_list" >> $GITHUB_OUTPUT

  specific-integrations:
    runs-on: ubuntu-latest
    needs: [get-input-list]
    strategy:
      matrix:
        path: ${{ fromJSON(needs.get-input-list.outputs.input-list) }}
    steps:
      - name: checkout
        if: inputs.${{ matrix.path }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: run integration
        if: inputs.${{ matrix.path }}
        uses: ./.github/actions/run_integration
        with:
          path: ${{ matrix.path }}

  after:
    runs-on: ubuntu-latest
    needs: [specific-integrations]
    steps:
      - run: echo "hello world"
